# Generated by Django 4.2.5 on 2023-11-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsiya', '0004_patientdischargedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='assignedDoctorId',
            new_name='assignedDoctor',
        ),
    ]
