# Generated by Django 4.2.5 on 2023-11-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapsiya', '0005_rename_assigneddoctorid_patient_assigneddoctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='assignedDoctor',
            new_name='assignedDoctorId',
        ),
    ]
